[project]
name = "sc-find"
version = "0.1.0"
description = "Add a short description here"
authors = ["Aaron Miller <apage43@ninjawhale.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
transformers = "4.34.0.*"
pillow = "10.0.1.*"
requests = "2.31.0.*"
pytorch = "2.0.0.*"
black = "23.9.1.*"
tqdm = "4.66.1.*"
ipykernel = "6.25.2.*"
bandit = "1.6.0.*"
ipywidgets = "8.1.1.*"
